source "https://rubygems.org"

gem "ipfs", require: 'ipfs/client'

gem 'bitcoin-ruby', require: "bitcoin"

#, git: 'https://github.com/lian/bitcoin-ruby', branch: 'master', require: 'bitcoin'

group :test do
  gem "rspec-core"
  gem "rspec-mocks"
  gem "rspec-expectations"
end
